Infleqtion/client-superstaq

- .github/workflows/ci.yml
- dev-requirements.txt
- requirements.txt
- setup.py
Two points I'm unsure about in this PR:
- looks like `supermarq` already has a `dev` version, but it's called `dev_env`.  Do we want to rename this to mirror `app-ss[dev] / css[dev] / qss[dev]`?
- should we require `css[dev]` and `qss[dev]` in `dev-requirements.txt`, or `app-ss[dev]`?
UPDATE: we will make it `supermarq[dev]`, and I made `dev-requirements.txt` require `app-ss[dev]`
> updates in light of check script changes

- README.md
This is to prevent people from being unable to run checks locally because they don't have dev requirements installed.
Related to [177](https://github.com/SupertechLabs/general-superstaq/issues/177)
> Add gss dev requirements installation to readme

- dev-requirements.txt
- requirements.txt
- supermarq/benchmarks/bit_code.py
- supermarq/benchmarks/phase_code.py
Credit to @knsmith for catching this.
The script
```python
import supermarq
bit_code = supermarq.benchmarks.bit_code.BitCode(
num_data_qubits=3, num_rounds=1, bit_state=[0, 0, 0]
)
print(bit_code.circuit())
```
formerly printed
```
0: ───@───────────────────────────────M('meas_all')───
│                               │
1: ───X───X───────────M('mcm0')───R───M───────────────
│           │               │
2: ───────@───@───────┼───────────────M───────────────
│       │               │
3: ───────────X───X───M───────────R───M───────────────
│                   │
4: ───────────────@───────────────────M───────────────
```
and now prints
```
0: ───@───────────────────────M('meas_all')───
│                       │
1: ───X───X───M('mcm0')───R───M───────────────
│   │               │
2: …
```
> roerder the operations in the bit/phase codes to reduce circuit depth

- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
previously [this check](https://github.com/SupertechLabs/client-superstaq/blob/main/general-superstaq/general_superstaq/superstaq_client.py#L363-L365) didn't catch anything, because `response.text` always contains the json-serialized response string, e.g.
```python
'"You must accept the Terms of Use (superstaq.super.tech/terms_of_use)."\n'
```
instead of just
```python
"You must accept the Terms of Use (superstaq.super.tech/terms_of_use)."
```
Calling `response.json()` instead deserializes the response content, and so returns the correct string for comparison
confirmed locally that after this change the message handling works as expected:
> fix terms of use checking

- general-superstaq/general_superstaq/check/coverage_.py
coverage doesn't really accept many other arguments we'd care about, so extra command line args should be passed to pytest instead. This way the same arguments (including `--randomly-seed=`) can be passed to `check/pytest_.py` and `check/coverage_.py`
fixes #414
> allow `--randomly-seed=` (and other pytest args) to be passed to coverage check

- general-superstaq/general_superstaq/superstaq_client_test.py
previously the part of the test which was supposed to read the key from a file would fail because the env variable took precedence
> mock environ in `test_find_api_key` so it passes when SUPERSTAQ_API_KEY is set locally

- supermarq-benchmarks/supermarq/converters.py
Fixes #407. Results in warning-free output, compare with #407:
```
...
supermarq-benchmarks/supermarq/benchmarks/mermin_bell_test.py ..                               [ 87%]
supermarq-benchmarks/supermarq/benchmarks/phase_code_test.py ...                               [ 96%]
supermarq-benchmarks/supermarq/converters_test.py .                                            [100%]
======================================== 31 passed in 36.14s =========================================
Name    Stmts   Miss    Cover   Missing
---------------------------------------
TOTAL    1007      0  100.00%
...
```
> Removes use of deprecated qubit index access

- check/pytest_.py
The deploy script fails because of these notebooks because there is a mismatch between the qiskit versions in the client and server. Will undo once we deploy the client.
> Temporarily ignore failing notebooks

- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
in response to bug reports from qscout users:
* changes default `mirror_swaps` value to False
* updates docstring of qscout_compile and aqt_compile (previously the qscout_compile contained an accidental reference to AQT)
> update docstrings and defaults for aqt_compile and qscout_compile

- cirq-superstaq/cirq_superstaq/compiler_output.py
- cirq-superstaq/cirq_superstaq/compiler_output_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
allows users to get compiled circuits for open qasm/non-pulse-enabled backends
> allow ibmq_compile to succeed if the server doesn't send back pulses

- cirq-superstaq/cirq_superstaq/job.py
- cirq-superstaq/cirq_superstaq/job_test.py
- general-superstaq/general_superstaq/superstaq_exceptions.py
- general-superstaq/general_superstaq/superstaq_exceptions_test.py
* consistent use of `gss.SuperstaqUnsuccessfulJobException` for failed jobs
* improve the error message in said exception
* raise TImeoutError if `job.counts()` times out but the job hasn't failed
* fix mocked statuses in css.job_test which previously weren't any of those in Job.ALL_STATES (in one case causing a test to pass which shouldn't have)
> clean up status handling in `css.Job`

- qiskit-superstaq/qiskit_superstaq/serialization.py
- qiskit-superstaq/qiskit_superstaq/serialization_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
(mostly just adds a custom converter/resolver to qss.serialization because numpy arrays aren't json-serializable)
confirmed this works locally after the corresponding server-side changes
part of #502
> support custom gate defs in qss

- qiskit-superstaq/setup.py
pip page for qiskit-superstaq points to the previous location of this source code, I think.
> pip page for qiskit-superstaq has a broken link

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
follow up to #566 - removes deprecated aqt_compile_eca calls from daily integration checks (instead uses `aqt_compile(..., num_eca_circuits=n)`)
also changes `num_equivalent_circuits` -> `num_eca_circuits` in `qss.compiler_output` for consistency with css
> remove deprecated calls from daily integration checks

- cirq-superstaq/cirq_superstaq/service.py
- qiskit-superstaq/qiskit_superstaq/serialization.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
in general input annotations should be as general as possible (especially for public-facing functions). these methods don't actually require that circuits be passed as a proper `list` instance (tuples of circuits work just as well, for example)
> generalize input annotations from `List[<circuit_type>]` to `Sequence[<circuit_type>]`

- cirq-superstaq/cirq_superstaq/service_test.py
- general-superstaq/general_superstaq/check/check_utils.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
These tests looks for a **failure** to find an API key, and therefore do not pass on my local machine: `qss` and `css` successfully find an API key in `~/.local/share/super.tech/superstaq_api_key`... as they should!
This bug breaks `./check/pytest_.py` and `./check/coverage_.py` for me locally.
Rather than adding more mocks, I think it is safe to remove these tests, since they are redundant with [`gss.superstaq_client_test.test_find_api_key`](https://github.com/Infleqtion/client-superstaq/blob/9779e5524b5b874d460608d9987979ca0bce85b9/general-superstaq/general_superstaq/superstaq_client_test.py#L702).
Also: nit bugfix in `check_utils.get_file_parser`, which caused the [default `--exclude` arguments](https://github.com/Infleqtion/client-superstaq/blob/9779e5524b5b874d460608d9987979ca0bce85b9 …
> remove broken + redundant API key tests in `css` and `qss`

- general-superstaq/pyproject.toml
otherwise check/configs_.py will fail if gss was pulled from pypi
> add checks-pyproject.toml to gss package_data

- general-superstaq/general_superstaq/check/format_.py
by default black will look for config files in the common parent directory of all the files it's checking. this causes `check/format_.py <files>` (or `check/format_.py -i`) to break if all the (modified) files were in the same subdirectory, because e.g. it will use `cirq-superstaq/pyproject.toml` instead of `./pyproject.toml`
> pass config file path to black

- cirq-superstaq/example-requirements.txt
- qiskit-superstaq/qiskit_superstaq/custom_gates.py
- qiskit-superstaq/qiskit_superstaq/custom_gates_test.py
- qiskit-superstaq/qiskit_superstaq/serialization.py
fixes a test and removes every instance of `gate.qasm()` (which is now deprecated)
> support for qiskit-terra 0.25.0

- general-superstaq/general_superstaq/qubo.py
- general-superstaq/general_superstaq/qubo_test.py
In `qubo.py`, the `convert_qubo_to_model` function previously was used to serialize a qubo before sending it in as a request. However, after finishing #681, there is no need for this function anymore - removed for cleanliness.
> Delete `convert_qubo_to_model` in `qubo.py`

- docs/source/get_started/access_info/access_info_css.ipynb
- docs/source/get_started/access_info/access_info_qss.ipynb
- docs/source/get_started/basics/basics_css.ipynb
- docs/source/get_started/basics/basics_qss.ipynb
Addresses most of https://github.com/Infleqtion/client-superstaq/issues/696 by allowing free-trial users to run the notebooks for now. 
The qss notebook requires https://github.com/Infleqtion/server-superstaq/pull/2631
> Update tutorials with `"dry-run"`

- qiskit-superstaq/qiskit_superstaq/custom_gates.py
- qiskit-superstaq/qiskit_superstaq/custom_gates_test.py
(fixes tests when upgrading to qiskit 0.44.1)
> use unicode π in more qss.custom_gates strings

- check/pytest_.py
these all seem to pass quickly, so afaict there's no reason to exclude them from tests
> remove some exclusions from notebook check

- cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py
Fixes https://github.com/Infleqtion/client-superstaq/issues/737
> Replace `np.array_equal` with `np.allclose` in `test_qudit_swap_gate`

- .github/workflows/daily-integration-check.yml
- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- general-superstaq/general_superstaq/service.py
- general-superstaq/general_superstaq/service_test.py
- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
These don't actually do anything, and can be safely removed.
> Remove token setting methods from the client interface

- cirq-superstaq/cirq_superstaq/serialization.py
- cirq-superstaq/cirq_superstaq/serialization_test.py
reverts https://github.com/Infleqtion/cirq-superstaq/pull/241 (which at the time was necessary because we supported `cirq<=0.14.*`)
> revert addition of "device" attribute to serialized circuits

- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
Fixes #782.
This primarily handles getting counts like `{"01": 500.0, "10": 500.0}`, where they're already whole numbers. For `float` results more generally, I claim it's enough to warn users since we also offer `service.get_counts` as a public method, but I'm open to ideas about how else to address this.
(Seems like we can't get around `cirq.ResultDict` needing a list/array of results for the `measurements` param, and we can't append half or a quarter of an array element...)
> Handle float counts + warn users

- .github/workflows/daily-integration-check.yml
- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
Hotfix for now. We probably want to put this as a separate test longterm so a different issue will be made by the bot when the test fails.
> Set timeout on Hilbert submission daily integration test to 5 minutes

- checks-superstaq/checks_superstaq/requirements.py
Main changes:
- Remove explicit check against `checks_superstaq.__version__`, making `checks-superstaq` independent of the other `*-superstaq` repos (and thereby more usable by independent projects such as `QFI-Opt` and `qLDPC`).
- When retrieving the the latest version of a package, take the `max` of the local version and that on PyPI.  If either the local or PyPI version of a package is not found, then that version is set to `0.0.0` before taking the `max`.
- The local package version is what replaces the call to `checks_superstaq.__version__` mentioned above.
- Remove an unnecessary check for whether `requirements.py` can connect to PyPI.  Either a package is retrieved from PyPI or it isn't.
> Cleanup in `requirements.py`

- .github/workflows/daily-integration-check.yml
- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
These tests make use of the TEST_USER_IBMQ_TOKEN that was already set up for testing the token setting methods that were removed.
> Add tests using a custom IBMQ token

- checks-superstaq/pyproject.toml
I got (at least) one line wrong when copying+modifying the `pyproject.toml` file from `general-superstaq`.  Fixing it here.
> fix incorrect line in checks-superstaq/pyproject.toml

- cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py
test is failing due to https://github.com/quantumlib/Cirq/issues/6376
(this seems to have been triggered by cirq the 1.3.0 update, though tbh i'm not sure why - the comparison logic doesn't seem to have changed in a way that would have caused this)
> remove failing check due to cirq bug

- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/compiler_output_test.py
this often fails if the user has an older version of qiskit. pulse schedules are deprecated anyway, so this shouldn't cause ibmq_compile to fail (the user should still have the corresponding pulse gate sequence)
> wrap pulse schedule deserialization in try..except block

- checks-superstaq/requirements.txt
- qiskit-superstaq/qiskit_superstaq/__init__.py
- qiskit-superstaq/qiskit_superstaq/custom_gates.py
- qiskit-superstaq/qiskit_superstaq/custom_gates_test.py
- qiskit-superstaq/qiskit_superstaq/serialization.py
- qiskit-superstaq/qiskit_superstaq/serialization_test.py
- qiskit-superstaq/requirements.txt
also adds workarounds for a number of known qpy bugs, and fixes some bugs in our previous implementation (which didn't recurse into gate .definitions, and therefore could break or silently modify gates if circuits weren't flattened prior to submission)
fixes: #837
(notebook checks won't pass until after this is deployed)
> rewrite `qss.serialize_circuits` to support newest qiskit

- qiskit-superstaq/example-requirements.txt
`qiskit-ibm-provider` is now part of qss's standard requirements, so doesn't need to be example-requirements too
> remove duplicate `qiskit-ibm-provider` req in qss/example-requirements

- cirq-superstaq/requirements.txt
Currently, `qubovert>=1.2.3` is in the `requirements.txt` of `general-superstaq`, and given that `cirq-superstaq` requires `general-superstaq`, I think the explicit requirement is not needed anymore
> Remove `qubovert` req in `css`

- .github/workflows/ci.yml
- qiskit-superstaq/requirements.txt
symengine is required to deserialize pulse gate circuits from superstaq. qiskit only requires `>=0.9.0`, but deserialization [will fail](https://github.com/symengine/symengine/blob/bbaed4724003b882c26ef09395d87f94c1d5a451/symengine/basic.cpp#L68) if server and client aren't using the same version (up to patch)
> pin symengine 0.11

- checks-superstaq/requirements.txt
- general-superstaq/requirements.txt
(pydantic isn't required by checks-superstaq itself)
> move pydantic req to gss

- qiskit-superstaq/example-requirements.txt
was removed from qss/requirements.txt in #884, but we still need it in the notebooks
> add mpl to qss example reqs

- general-superstaq/requirements.txt
Not needed due to https://github.com/Infleqtion/client-superstaq/pull/883
See https://github.com/Infleqtion/client-superstaq/pull/788/files#r1373726825 for more context.
> Remove `pydantic` upper bound

- supermarq-benchmarks/supermarq/converters.py
While looking through the code, I couldn't help but notice that the computation of the critical depth is unnecessarily wasteful since it would repeatedly compute `dag.count_ops_longest_path()`.
Furthermore, this PR uses a arguably more Pythonic and concise way of computing `n_ed`.
> Optimize critical depth computation

- cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py
currently we don't rotate the vertical bars over the qubit wires for transposed diagrams, so they don't really look much like barriers:
```
0 1 2 3
│ │ │ │
H X─┼─@
│ │ │ │
│─│─│ │
│ │ │ │
```
after this pr they're much more apparent (and consistent with the horizontal diagram):
```
0 1 2 3
│ │ │ │
H X─┼─@
│ │ │ │
───── │
│ │ │ │
```
> fix barrier symbol in transposed diagrams

- docs/source/get_started/access_info/access_info_qss.ipynb
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
Fixes an issue with `ss_unconstrained_simulator` being excluded from a `qiskit_superstaq.SuperstaqProvider().backends()` call after recent updates such as https://github.com/Infleqtion/client-superstaq/pull/914.
> Add `supports_submit_qubo` filter to `backends()`

- qiskit-superstaq/qiskit_superstaq/__init__.py
- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/compiler_output_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
replaces `measured_clbit_indices` (which returns a list of clbit indices) with `classical_bit_mapping` (which returns a dictionary mapping those indices to the indices of the measured qubit)
> `measured_clbit_indices` to `classical_bit_mapping`

- .github/integration-check-failure-issue.md
- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
Due to `test_ibmq_compile_with_token()` consistently failing the daily integration tests, this PR adds a `pytest.mark.skip` temporarily till the underlying issue is resolved. 
(Also adds a label to be added for the bot)
> Temp skip of `test_ibmq_compile_with_token()`

- supermarq-benchmarks/supermarq/converters.py
- supermarq-benchmarks/supermarq/converters_test.py
- supermarq-benchmarks/supermarq/features_test.py
As discussed in #895, this PR refactors the implementation of the parallelism feature to align with the description from the original paper https://arxiv.org/abs/2202.11045. The implementation takes extra care to avoid corner cases where divisions by zero could happen.
Fixes #895
> ♻️ compute parallelism feature as described in `arXiv:2202.11045`

- supermarq-benchmarks/supermarq/benchmarks/hamiltonian_simulation.py
- supermarq-benchmarks/supermarq/benchmarks/mermin_bell.py
significantly speeds up the mermin bell constructor by removing the expensive sympy logic in `_mermin_operator` (instead we can just iterate over every pauli string with an odd number of Ys, with eigenvalues `(-1)**((num_ys-1)/2)`) (something similar is described in https://arxiv.org/pdf/2005.11271)
constructor times before:
```
MerminBell(8):  0.553s
MerminBell(10): 2.998s
MerminBell(12): 18.75s
MerminBell(14): 82.12s
```
after:
```
MerminBell(8):  0.001s
MerminBell(10): 0.003s
MerminBell(12): 0.010s
MerminBell(14): 0.043s
...
MerminBell(18): 0.815s
MerminBell(20): 4.515s
```
> speed up mermin bell benchmark

- supermarq-benchmarks/supermarq/benchmarks/ghz.py
- supermarq-benchmarks/supermarq/benchmarks/ghz_test.py
allows selection between a "ladder" circuit (the current implementation), "star" (the typical GHZ structure, with all CNOTs sharing the same control), and "fanout" (using a log-depth fanout circuit)
> add `method=` argument to GHZ benchmark

- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
`qiskit.providers.Provider` [has been deprecated](https://github.com/Qiskit/qiskit/blob/473c3c2e58f855332532c2c47a11db5695c0180f/qiskit/providers/provider.py#L47-L52). we don't inherit anything from it anyway.
> remove qiskit.providers.Provider inheritence

- qiskit-superstaq/qiskit_superstaq/custom_gates.py
Fixes #953 compilation error:
```python
import qiskit_superstaq as qss
provider = qss.SuperstaqProvider()
brisbane = provider.get_backend("ibmq_brisbane_qpu")
theta = qiskit.circuit.Parameter("θ")
qc = qiskit.QuantumCircuit(2, 2)
qc.append(qss.AceCR(theta), (0, 1))
qc.measure((0, 1), (0, 1))
qc_bound = qc.assign_parameters({theta: np.pi / 3})
brisbane.compile(qc_bound)
```
> Store `AceCR` properties in `self.params`

- general-superstaq/general_superstaq/validation.py
- general-superstaq/general_superstaq/validation_test.py
Addresses part of https://github.com/Infleqtion/client-superstaq/issues/958 by unblocking the `backends()` endpoint of `qiskit-superstaq`. 
Will also allow calls to the `compile` endpoint with `iqm_*` backends (though further optimization may be needed).
> Remove prefix hardcoding in `validate_target()`

- checks-superstaq/checks_superstaq/checks-pyproject.toml
- checks-superstaq/checks_superstaq/coverage_.py
- checks-superstaq/checks_superstaq/pytest_.py
- checks-superstaq/requirements.txt
- Updating the .toml file to include overall disable-socket.
- Updating the pytest_.py and coverage_.py file to use the "--force-enable-socket" flag under notebook and integration statements.
Closes #962
> Disable socket

- checks-superstaq/checks_superstaq/checks-pyproject.toml
- checks-superstaq/checks_superstaq/init_return.py
- checks-superstaq/checks_superstaq/pylint_init_return.py
- general-superstaq/general_superstaq/superstaq_client.py
The return type annotation for `__init__` is inconsistently enforced by `mypy`. The plugin will warn when there is no explicit return type annotation and when the return type in the annotation is not `None`.
> Pylint plugin to check that return type annotation for `__init__` functions is `-> None`

- checks-superstaq/checks_superstaq/check_utils.py
- checks-superstaq/checks_superstaq/coverage_.py
> support both `<x>_test.py` and `test_<x>.py` for test discovery

- qiskit-superstaq/example-requirements.txt
- qiskit-superstaq/qiskit_superstaq/serialization.py
- qiskit-superstaq/qiskit_superstaq/serialization_test.py
- qiskit-superstaq/requirements.txt
qiskit-ibm-provider is deprecated, so this removes it from user-facing code/requirements. We still use it in a few places in the docs; these should also be updated so we can drop it from example-requirements too
requires us to bump our qiskit req to 1.0.0, hopefully this has been around long enough that it isn't an issue for anyone
> drop qiskit-ibm-provider from qss

- checks-superstaq/checks_superstaq/pytest_.py
changes the argument order in the subprocess call to pytest to allow manually overriding of the number of threads (or disabling multithreading altogether with `pytest_.py .... -n0`)
partially addresses #990, but as per that issue we should also consider changing the default (and maybe even choosing it dynamically based on the number of files we're testing?)
> allow overriding number of pytest threads

- checks-superstaq/checks_superstaq/checks-pyproject.toml
- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- cirq-superstaq/cirq_superstaq/job_test.py
- cirq-superstaq/cirq_superstaq/ops/qudit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py
- cirq-superstaq/cirq_superstaq/service.py
- general-superstaq/general_superstaq/service.py
- qiskit-superstaq/qiskit_superstaq/conftest.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py
- supermarq-benchmarks/supermarq/benchmark.py
- supermarq-benchmarks/supermarq/benchmark_test.py
- supermarq-benchmarks/supermarq/benchmarks/qaoa_vanilla_proxy.py
- supermarq-benchmarks/supermarq/plotting.py
Although we import the `docparams` plugin from pylint's extensions, the checks for ensuring docstrings contain return, yield, parameter, and raise documentation are optional and not enabled. We have been enforcing the inclusion of these through pr reviews.
> Enable docparams checks

- cirq-superstaq/cirq_superstaq/job.py
- cirq-superstaq/cirq_superstaq/job_test.py
- cirq-superstaq/docs/getting_started_cirq_superstaq.ipynb
- cirq-superstaq/docs/ibm_cirq_superstaq.ipynb
- docs/source/get_started/basics/basics_css.ipynb
- docs/source/optimizations/ibm/ibmq_compile_css.ipynb
for backwards compatibility #691 added a special case treating `index=None` like `index=0`, with a deprecation warning, when retrieving some attributes from css jobs containing a single circuit. It's now been ~9 months, so we can probably drop this in favor of more consistent return typing
> drop deprecated css.Job indexing functionality

- cirq-superstaq/cirq_superstaq/job_test.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py
adds `_commutes_` and `_commutes_on_qids_` magic methods to `css.Barrier` to indicate that barriers should never commute
(also adds one line in `job_test.py` to prevent a superfluous warning from appearing in the pytest output)
> barriers should never commute

- cirq-superstaq/cirq_superstaq/validation.py
- cirq-superstaq/cirq_superstaq/validation_test.py
Fixes https://github.com/Infleqtion/client-superstaq/issues/1011
> Validate qubit types in `css`

- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py
- supermarq-benchmarks/supermarq/qcvv/conftest.py
- supermarq-benchmarks/supermarq/qcvv/irb.py
- supermarq-benchmarks/supermarq/qcvv/irb_test.py
- supermarq-benchmarks/supermarq/qcvv/xeb.py
- supermarq-benchmarks/supermarq/qcvv/xeb_test.py
currently some progress bars only work correctly in a notebook environment. this is fixed by importing from `tqdm.auto` instead of `tqdm.notebook`
also moves `patch_tqdm` to qcvv/conftest.py to avoid repetition in each test file
> fix qcvv progress bars when using cli

- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py
- supermarq-benchmarks/supermarq/qcvv/irb_test.py
- supermarq-benchmarks/supermarq/qcvv/xeb_test.py
currently instantiating a qcvv experiment will fail if a `css.Service` can't be constructed, even if we don't require superstaq functionality
> allow instantiation of qcvv experiments without superstaq credentials

- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
allows users to see targets available with provided credentials
> pass service kwargs to get_targets

- checks-superstaq/checks_superstaq/checks-pyproject.toml
- supermarq-benchmarks/supermarq/benchmarks/qaoa_fermionic_swap_proxy.py
- supermarq-benchmarks/supermarq/benchmarks/qaoa_vanilla_proxy.py
- supermarq-benchmarks/supermarq/qcvv/conftest.py
most of the code in QAOAFermionicSwapProxy is identical to that of QAOAVanillaProxy, so instead of repeating it we can inherit
> factor out shared code in qaoa proxies

- checks-superstaq/checks_superstaq/requirements.py
pip allows packages to be specified by location (e.g. a git repo), but this will fail the requirements check because `@` isn't a version restriction
> allow locations in requirements files

- docs/source/_static/css/docs-superstaq.css
Fixes the spurious colons generated in the API summary in the docs. Achieved by hiding the `colon` class in our `.css`.
Supercedes https://github.com/Infleqtion/client-superstaq/pull/944
> Fix spurious colon

- qiskit-superstaq/requirements.txt
Solving #1080. Locally ran the `resource_esitmate.ipynb`, `qscout_tutorial.ipynb`, and basic submissions to backends successfully with the updated pin.
> Update symengine version to 0.13.0

- docs/source/optimizations/eeroq/eeroq_css.ipynb
- docs/source/optimizations/eeroq/eeroq_qss.ipynb
I accidentally set the subheadings to be headings, so the readthedocs contents list is inaccurate.
> Fixing headers in EeroQ demo notebooks

- checks-superstaq/checks_superstaq/checks-pyproject.toml
`taplo fmt <file>` will format TOML files.
Maybe I should add https://pypi.org/project/taplo/ and use it in `checks/format_.py`?  Might not be worth the extra dependency though.
I mostly want this change because I want to format my TOML files in other projects (in particular, `pyproject.toml`), but that causes `checks/configs.py` to fail 🙂
> Format TOML files with taplo

- docs/source/apps/supermarq/qcvv/qcvv_css.ipynb
- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py
- supermarq-benchmarks/supermarq/qcvv/irb.py
- supermarq-benchmarks/supermarq/qcvv/irb_test.py
- supermarq-benchmarks/supermarq/qcvv/xeb.py
- supermarq-benchmarks/supermarq/qcvv/xeb_test.py
Rename `circuit_index` -> `circuit_realization` in the QCVV `Sample` object to avoid possible confusion
> Rename `circuit_index` in QCVV library

- general-superstaq/requirements.txt
versions before 2.32.0 have known vulnerabilities: https://osv.dev/vulnerability/PYSEC-2023-74, https://osv.dev/vulnerability/GHSA-9wx4-h78v-vm56
> bump min version of requests

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
Not passing in `css.AceCR` cause they can't be serialized anymore.
> Don't pass in `css.AceCR` to `daily_integration_test.py`

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
Fixes: https://github.com/Infleqtion/client-superstaq/issues/1173
Seems related to https://github.com/Infleqtion/client-superstaq/issues/1170, but calling the compiled pulse gate circuit on an input circuit such as:
```python
circuit = cirq.Circuit(
css.AceCRMinusPlus(qubits[0], qubits[1]),
css.AceCRMinusPlus(qubits[1], qubits[2]),
css.AceCRMinusPlus(qubits[2], qubits[3]),
)
```
yields`None`.
Following https://github.com/Infleqtion/client-superstaq/pull/1169, this PR replaces the input circuit in the meantime till https://github.com/Infleqtion/client-superstaq/issues/1170 is addressed
> Drop `css.AceCRMinusPlus` in `css` integration test

- general-superstaq/general_superstaq/_models.py
- general-superstaq/general_superstaq/_models_test.py
- general-superstaq/requirements.txt
Investigating https://github.com/Infleqtion/client-superstaq/issues/1171
What I found is as follows:
1. Pydantic V1 is quite out of date now and only has security patch updates. I suggest we move away from it (hence updated the requirements.txt to a much more recent  version of pydantic. 
2. In order for pydantic to play nicely with older versions of python (3.8 & 3.9) I needed to change how the default model config was implemented and add a package `eval_type_backport` which allows pydantic to recognize modern type hinting when running on older python versions (e.g. `list` rather than `typing.List` and `|` rather than `typing.Union`). Unfortunately pydantic does not seem to use `__future__annotations` natively.
3. I've now added a single test that checks whether pydantic can load models …
> Add models test

- .github/workflows/ci.yml
- general-superstaq/requirements.txt
This PR makes `eval_type_backport` somewhat optional in the spirit of minimal package dependencies.
It also serves as a reminder to remove the requirement when Python 3.9 support is dropped.
> Ignore `eval_type_backport` if `python_version > '3.9'`

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
Fixes: https://github.com/Infleqtion/client-superstaq/issues/1170 by reverting https://github.com/Infleqtion/client-superstaq/pull/1174 & https://github.com/Infleqtion/client-superstaq/pull/1169
> Add `AceCR` gate in integration tests

- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py
- supermarq-benchmarks/supermarq/qcvv/xeb.py
- supermarq-benchmarks/supermarq/qcvv/xeb_test.py
adds two convenience methods:
* `BaseExperiment.circuits` (a shortcut to `[sample.circuit for sample in experiment]`)
* `XEB.independent_qubit_groups()` (to get independent subgroups for parallel XEB)
> helper functions for qcvv protocols

- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py
fixes `backend.target` error when the backend's `target_info` doesn't contain timing constraints
> fix `backend.target` failures for missing target_info

- checks-superstaq/checks_superstaq/pytest_.py
Various notebook check timeouts/failures, like in https://github.com/Infleqtion/client-superstaq/issues/1129, may potentially be attributed to spawning too many kernels in a short amount of time, trying to use a port already in use. This PR hence limits the number of threads to a maximum of four in an effort to reduce the likelihood of such scenarios from happening.
As of this PR, the number of workers currently spawned by each notebook check is:
- `cirq-superstaq`: 9 workers
- `qiskit-superstaq:` 8 workers
- `supermarq-benchmarks`: 6 workers
> Upper bound notebook `pytest` threads to 4
