- README.md
Fixes: https://github.com/SupertechLabs/SupermarQ/issues/7
> Badge for CI

- supermarq/__init__.py
> make version number importable

- setup.cfg
> ignore flake8 E203 errors (which conflict with black)

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yaml
Changing 'about' key to 'description'
> Update feature request issue form

- requirements.txt
- setup.cfg
- supermarq/benchmark_test.py
- supermarq/benchmarks/bit_code.py
- supermarq/benchmarks/bit_code_test.py
- supermarq/benchmarks/ghz_test.py
- supermarq/benchmarks/hamiltonian_simulation.py
- supermarq/benchmarks/mermin_bell.py
- supermarq/benchmarks/phase_code.py
- supermarq/benchmarks/phase_code_test.py
- supermarq/benchmarks/qaoa_fermionic_swap_proxy.py
- supermarq/benchmarks/qaoa_fermionic_swap_proxy_test.py
- supermarq/benchmarks/qaoa_vanilla_proxy.py
- supermarq/benchmarks/vqe_proxy.py
- supermarq/plotting.py
- supermarq/simulation.py
- supermarq/stabilizers.py
extends https://github.com/SupertechLabs/general-superstaq/pull/167 to supermarq in anticipation of repo merge
> remove generic types

- dev-requirements.txt
- setup.cfg
- supermarq/benchmarks/mermin_bell.py
Part of https://github.com/SupertechLabs/general-superstaq/issues/49
> Add `flake8-type-checking`

- check/build_docs.py
- docs/requirements.txt
- docs/source/index.rst
- docs/source/supermarq.rst
Updated requirements, `build_docs.py` in check. Ran `build_docs.py to make `supermarq.rst` and added supermarq to `index.rst`
> Add supermarq to docs

- supermarq-benchmarks/examples/SupermarQ_HPCA_Tutorial.ipynb
- supermarq-benchmarks/examples/ghz_example.py
- supermarq-benchmarks/supermarq/_version_test.py
- supermarq-benchmarks/supermarq/converters_test.py
- supermarq-benchmarks/supermarq/features.py
- supermarq-benchmarks/supermarq/features_test.py
- supermarq-benchmarks/supermarq/plotting_test.py
> Remove import as sm

- cirq-superstaq/cirq_superstaq/__init__.py
- cirq-superstaq/cirq_superstaq/ops/__init__.py
- cirq-superstaq/cirq_superstaq/ops/qudit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py
(useful for routing qudit circuits)
> add `css.QuditSwapGate`

- qiskit-superstaq/qiskit_superstaq/__init__.py
- qiskit-superstaq/qiskit_superstaq/custom_gates.py
- qiskit-superstaq/qiskit_superstaq/custom_gates_test.py
Porting [qss#322](https://github.com/SupertechLabs/qiskit-superstaq/pull/322) via copy/paste
@richrines1 you approved this previously, your call on whether to simply approve again or take another pass.
> Add StrippedCZ to qss

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
Related to [ss-2051](https://github.com/SupertechLabs/server-superstaq/pull/2051) (which still needs to be reviewed)
> Daily integration tests for setting CQ token

- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
Ported code to address issue #381
> Getting superstaq version from metadata

- general-superstaq/general_superstaq/check/coverage_.py
corrects my somewhat embarrassing mistake in #416
> correctly pass `--disable-socket` in coverage check

- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
...and remove most of the mocking/monkeypatching in `qss.superstaq_job_test`
> call `_client.get_job` instead of duplicating it in `superstaq_job`

- general-superstaq/general_superstaq/check/check_utils.py
fixes #437
fixes #439
fixes #440
> stop trying to check deleted files

- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
- general-superstaq/general_superstaq/superstaq_client.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
Address https://github.com/SupertechLabs/client-superstaq/issues/404
> Add options to cq_compile

- cirq-superstaq/cirq_superstaq/compiler_output.py
- cirq-superstaq/dev-requirements.txt
- qiskit-superstaq/requirements.txt
Part of https://github.com/SupertechLabs/server-superstaq/pull/2224
> Update `qiskit-terra` version to `0.23.*`

- docs/source/conf.py
(Another minor commitment to get myself back in the habit of coding!)
> Update copyright on docs

- .github/workflows/ci.yml
(currently they're both just re-checking gss)
> fix standalone css and qss checks

- cirq-superstaq/cirq_superstaq/service.py
- general-superstaq/dev-requirements.txt
- general-superstaq/general_superstaq/check/setup.cfg
increases the minimum versions of some of the testing packages we require (the checks won't all pass with the current minima)
i've confirmed everything now passes using the minimum and maximum versions of each req
> update check requirements

- cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py
- cirq-superstaq/requirements.txt
- docs/requirements.txt
we no longer need to support cirq 0.14.*
closes #242
> update cirq req to >=1.0.0

- qiskit-superstaq/qiskit_superstaq/compiler_output.py
Docstrings for `qiskit-superstaq/qiskit_superstaq/compiler_output.py`.
> `compiler_output` docstrings

- general-superstaq/general_superstaq/finance.py
- general-superstaq/general_superstaq/qubo.py
Minor change to lowercase Superstaq
> Docstring update in `finance.py` & `qubo.py`

- supermarq-benchmarks/supermarq/benchmarks/bit_code.py
> `BitCode` docstrings

- general-superstaq/general_superstaq/superstaq_exceptions.py
Added missing attribute for Superstaq exception base class + `q -> Q` in docstrings.
> Minor attribute addition.

- docs/source/optimizations/ibm/ibm.rst
> Make references in Superstaq for IBMQ a subsection

- cirq-superstaq/cirq_superstaq/__init__.py
- cirq-superstaq/cirq_superstaq/compiler_output.py
- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
- cirq-superstaq/cirq_superstaq/validation.py
- cirq-superstaq/cirq_superstaq/validation_test.py
- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
Fixes https://github.com/Infleqtion/client-superstaq/issues/594 + adds validation.py in parity with qss.
> Calling `aqt/qscout_compile` in ` css.Service.compile()`

- cirq-superstaq/cirq_superstaq/job.py
- cirq-superstaq/cirq_superstaq/job_test.py
- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
- docs/source/apps/max_sharpe_ratio_optimization.ipynb
- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
- general-superstaq/general_superstaq/user_config.py
- general-superstaq/general_superstaq/user_config_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
Reverts Infleqtion/client-superstaq#603
> Revert "rename all instances of `_SuperstaqClient` to `SuperstaqClient`"

- docs/source/get_started/basics/basics_css.ipynb
- docs/source/get_started/basics/basics_qss.ipynb
Remove highlighted text and added install instructions
> Update basics tutorials

- docs/source/cirq_superstaq.rst
- docs/source/general_superstaq.rst
edits that needed to be made in the `general_superstaq.rst` file for renaming / removal purposes.
> needed to rename userconfig to service and remove finance / logistics in `general_superstaq.rst`

- general-superstaq/general_superstaq/validation.py
i think this caused the latest server deploy to fail
> Update quantinuum prefix

- cirq-superstaq/docs/getting_started_cirq_superstaq.ipynb
- cirq-superstaq/docs/ibm_cirq_superstaq.ipynb
- docs/source/apps/max_sharpe_ratio_optimization.ipynb
- docs/source/apps/supercheq/Supercheq_css.ipynb
- docs/source/apps/supercheq/Supercheq_qss.ipynb
- docs/source/get_started/access_info/access_info_css.ipynb
- docs/source/get_started/access_info/access_info_qss.ipynb
- docs/source/get_started/basics/basics_css.ipynb
- docs/source/get_started/basics/basics_qss.ipynb
- docs/source/index.rst
- docs/source/optimizations/aqt/aqt_css.ipynb
- docs/source/optimizations/aqt/aqt_qss.ipynb
- docs/source/optimizations/hilbert/hilbert_compile_css.ipynb
- docs/source/optimizations/hilbert/hilbert_compile_qss.ipynb
- docs/source/optimizations/ibm/ibmq_compile_css.ipynb
- docs/source/optimizations/ibm/ibmq_compile_qss.ipynb
- docs/source/optimizations/qscout/qscout_qss.ipynb
- qiskit-superstaq/examples/qscout_tutorial.ipynb
> Standardize notebook comments 

- cirq-superstaq/cirq_superstaq/job.py
- cirq-superstaq/cirq_superstaq/job_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py
fix https://github.com/Infleqtion/client-superstaq/issues/644
> Add `to_dict` to job classes

- docs/source/_static/svg/code.svg
Closes https://github.com/Infleqtion/client-superstaq/issues/649
> Update readme animation

- docs/source/apps/dfe/dfe.rst
- docs/source/apps/dfe/dfe_css.ipynb
- docs/source/apps/dfe/dfe_qss.ipynb
- docs/source/apps/max_sharpe_ratio_optimization.ipynb
- docs/source/apps/supercheq/Supercheq_css.ipynb
- docs/source/apps/supercheq/Supercheq_qss.ipynb
now that we are sure the content for the notebook renders correctly in read the docs, this adds the `qiskit-superstaq` equivalent of the dfe tutorial 
and colab/binder links fix
> Add `qiskit-superstaq` DFE tutorial

- .github/workflows/ci.yml
- .github/workflows/daily-integration-check.yml
- .github/workflows/main.yml
- .github/workflows/monthly-benchmarking-run.yml
(also renames '.github/workflows/montly-benchmarking-run.yml' to '.github/workflows/monthly-benchmarking-run.yml')
> update github actions to most recent versions

- supermarq-benchmarks/supermarq/run_benchmarks.py
close https://github.com/Infleqtion/client-superstaq/issues/657
> Check target info for mid-circuit measurement support in benchmark runs

- cirq-superstaq/cirq_superstaq/compiler_output_test.py
- cirq-superstaq/cirq_superstaq/ops/qudit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qudit_gates_test.py
- cirq-superstaq/cirq_superstaq/service_test.py
- general-superstaq/dev-requirements.txt
- general-superstaq/general_superstaq/qubo_test.py
- general-superstaq/general_superstaq/service_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
(newer versions don't allow empty lines at the top of function definitions, so various files had to be reformatted)
> allow newest black version

- general-superstaq/general_superstaq/typing.py
Typing update before merging https://github.com/Infleqtion/server-superstaq/pull/2608 (see [comment](https://github.com/Infleqtion/server-superstaq/pull/2608#discussion_r1293703314))
> Add `"input_circuit"` & `"circuit_type"` to `Job` in `gss.typing.py`

- cirq-superstaq/README.md
- cirq-superstaq/cirq_superstaq/sampler.py
- cirq-superstaq/docs/access.md
- cirq-superstaq/docs/getting_started_cirq_superstaq.ipynb
- dev_tools/locust.conf
- docs/source/apps/max_sharpe_ratio_optimization.ipynb
- docs/source/get_started/basics/basics_css.ipynb
- docs/source/get_started/basics/basics_qss.ipynb
- docs/source/get_started/credentials.rst
- docs/source/optimizations/hilbert/hilbert_compile_css.ipynb
- docs/source/optimizations/hilbert/hilbert_compile_qss.ipynb
- general-superstaq/general_superstaq/_init_vars.py
- general-superstaq/general_superstaq/service.py
- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
- qiskit-superstaq/README.md
- qiskit-superstaq/qiskit_superstaq/conftest.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- supermarq-benchmarks/README.md
> Update Superstaq URL to `superstaq.infleqtion.com`

- .github/workflows/ci.yml
Will comment back in once deploy is done.
> Temp comment out notebook checks

- docs/source/optimizations/ibm/ibmq_compile_css.ipynb
- docs/source/optimizations/ibm/ibmq_compile_qss.ipynb
- docs/source/optimizations/ibm/ibmq_dd.ipynb
Working notebook cells copied from Hilbert notebook.  Tested by locally building the docs.
> Fix IBMQ compile notebook links to Colab/binder

- cirq-superstaq/example-requirements.txt
- qiskit-superstaq/example-requirements.txt
google-colab 1.0.0 requires notebook==6.5.5
> Update notebook reqs

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
Remove simple test and refine the `assert of https://github.com/Infleqtion/client-superstaq/pull/777
> Stricter assert for Hilbert integration test

- general-superstaq/general_superstaq/__init__.py
- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
- general-superstaq/general_superstaq/superstaq_exceptions.py
adds a `SuperstaqWarning` class, and a mechanism for receiving warnings from the server
> support for superstaq warnings

- .github/CODEOWNERS
- .github/workflows/daily-integration-check.yml
- .github/workflows/monthly-benchmarking-run.yml
- checks-superstaq/checks_superstaq/format_.py
- checks-superstaq/checks_superstaq/requirements.py
> change `check/*` to `checks/*`

- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
Added description to configuration dictionary for SuperstaqBackend
> included description

- checks-superstaq/requirements.txt
the previous lower bounds of a few requirements were too low for our tests to pass
> update some checks-superstaq reqs

- checks-superstaq/checks_superstaq/all_.py
- checks-superstaq/checks_superstaq/build_docs.py
- checks-superstaq/checks_superstaq/check_utils.py
- checks-superstaq/checks_superstaq/checks-pyproject.toml
- checks-superstaq/checks_superstaq/configs.py
- checks-superstaq/checks_superstaq/coverage_.py
- checks-superstaq/checks_superstaq/flake8_.py
- checks-superstaq/checks_superstaq/format_.py
- checks-superstaq/checks_superstaq/mypy_.py
- checks-superstaq/checks_superstaq/pylint_.py
- checks-superstaq/checks_superstaq/pytest_.py
- checks-superstaq/checks_superstaq/requirements.py
- docs/source/conf.py
Update typing annotations for all checks files
> Modern annotations update to `checks-superstaq` (+ docs)

- docs/source/optimizations/ibm/ibmq_compile_css.ipynb
- docs/source/optimizations/ibm/ibmq_compile_qss.ipynb
> Remove `perth` in IBMQ docs

- checks-superstaq/checks_superstaq/check_utils.py
- checks-superstaq/requirements.txt
- cirq-superstaq/cirq_superstaq/job.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py
- cirq-superstaq/cirq_superstaq/service.py
- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
- supermarq-benchmarks/supermarq/benchmarks/qaoa_fermionic_swap_proxy.py
black versions 23.* and 24.* are not compatible, so this updates our minimum requirement to the latter (and reformats accordingly)
> update black req

- cirq-superstaq/cirq_superstaq/ops/qubit_gates.py
- cirq-superstaq/cirq_superstaq/ops/qubit_gates_test.py
> fix deserialization of msgate in css

- cirq-superstaq/cirq_superstaq/compiler_output.py
- cirq-superstaq/cirq_superstaq/compiler_output_test.py
- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/compiler_output_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
these haven't been used (or maintained) in ages
> drop .pulse_lists from aqt_compile

- checks-superstaq/checks_superstaq/configs.py
- cirq-superstaq/cirq_superstaq/compiler_output.py
- cirq-superstaq/cirq_superstaq/compiler_output_test.py
- cirq-superstaq/cirq_superstaq/serialization.py
- qiskit-superstaq/qiskit_superstaq/compiler_output.py
- qiskit-superstaq/qiskit_superstaq/compiler_output_test.py
- qiskit-superstaq/qiskit_superstaq/serialization.py
- qiskit-superstaq/qiskit_superstaq/serialization_test.py
among other things enables qiskit's timeline viewer
> add gate timing to pulse gate circuits

- general-superstaq/general_superstaq/superstaq_client.py
- general-superstaq/general_superstaq/superstaq_client_test.py
all qiskit devices are pulse devices now
> drop references to qiskit_pulse

- checks-superstaq/checks_superstaq/pytest_.py
- checks-superstaq/requirements.txt
Use pytest-xdist for faster pytest tests
> Add mulitcore support for pytest

- cirq-superstaq/cirq_superstaq/service.py
- cirq-superstaq/cirq_superstaq/service_test.py
- general-superstaq/general_superstaq/service.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider_test.py
(these will override pre-uploaded configs)
> allow passing qtrl configs to aqt_compile()

- checks-superstaq/checks_superstaq/pytest_.py
> Add option to disable multicore and auto disable when only 1 file

- qiskit-superstaq/qiskit_superstaq/conftest.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_backend.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
> lazy-load qss backend configuration

- checks-superstaq/requirements.txt
> add ruff to requirements.txt

- supermarq-benchmarks/examples/Supermarq_HPCA_Tutorial_css.ipynb
- supermarq-benchmarks/examples/Supermarq_HPCA_Tutorial_qss.ipynb
- supermarq-benchmarks/supermarq/plotting.py
- supermarq-benchmarks/supermarq/plotting_test.py
Fixes type check issues found in https://github.com/Infleqtion/client-superstaq/pull/1018 and addresses https://github.com/Infleqtion/client-superstaq/pull/1018#discussion_r1710428304
> Fix some input type issues in `supermarq-benchmarks/supermarq.plotting.py`

- qiskit-superstaq/qiskit_superstaq/superstaq_job.py
- qiskit-superstaq/qiskit_superstaq/superstaq_job_test.py
For some `qss` parity with https://github.com/Infleqtion/client-superstaq/pull/1034
> Support sub-job status checking & cancelling in `qss`

- docs/source/apps/supermarq/qcvv/qcvv_irb_css.ipynb
Fixes https://github.com/Infleqtion/client-superstaq/issues/1058
> Binder/Colab badge for IRB notebook

- qiskit-superstaq/qiskit_superstaq/custom_gates.py
Fixes https://github.com/Infleqtion/client-superstaq/issues/1045
> Update typing of `__array__` dunder methods

- supermarq-benchmarks/supermarq/qcvv/irb.py
- supermarq-benchmarks/supermarq/qcvv/irb_test.py
Adds the option to pass no interleaving gate to the IRB module in which case vanilla RB is performed
> Add functionality for RB

- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/irb.py
- supermarq-benchmarks/supermarq/qcvv/irb_test.py
- supermarq-benchmarks/supermarq/qcvv/xeb.py
- supermarq-benchmarks/supermarq/qcvv/xeb_test.py
(for reproducible circuit generation/simulation without side effects)
> allow qcvv routines to be initialized with a random seed

- qiskit-superstaq/requirements.txt
Temporary pin for failing checks
> Pin qiskit `v1.3.0`

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- docs/source/get_started/access_info/access_info_css.ipynb
- docs/source/get_started/access_info/access_info_qss.ipynb
- general-superstaq/general_superstaq/_models.py
- general-superstaq/general_superstaq/service.py
- general-superstaq/general_superstaq/testing.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/superstaq_provider.py
Fixes https://github.com/Infleqtion/client-superstaq/issues/1133 but more broadly updates documentation to mention the new `accessible` filter and `get_my_targets()` method.
> Usage & documentation of `accessible` filter & `get_my_targets()`

- general-superstaq/general_superstaq/_models.py
Small changes needed for some changes server-side
> Minor changes to the new server _models.py package

- general-superstaq/general_superstaq/_models.py
Minor update to new server models
> Add SIMULATING circuit state to new server models

- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/irb.py
- supermarq-benchmarks/supermarq/qcvv/xeb.py
Fixes format check failures in CI
> Format update from new `black` version 

- general-superstaq/general_superstaq/_models.py
Needed for https://github.com/Infleqtion/server-superstaq/pull/3491
> Minor changes to models for JobRefactor

- qiskit-superstaq/requirements.txt
Hotfix for https://github.com/Infleqtion/client-superstaq/issues/1175. Will make an issue to address compatibility issues in future PR
> Temp pin qiskit `v2.0.0`

- supermarq-benchmarks/supermarq/qcvv/base_experiment.py
- supermarq-benchmarks/supermarq/qcvv/base_experiment_test.py
- supermarq-benchmarks/supermarq/qcvv/irb.py
- supermarq-benchmarks/supermarq/qcvv/xeb.py
removes the custom `_from_json_dict_` methods from qcvv classes
> clean up qcvv json resolution

- cirq-superstaq/cirq_superstaq/service.py
Fixes recently failing [type check](https://github.com/Infleqtion/client-superstaq/actions/runs/15173065318/job/42667569485)
> Typing update for `_objective()` in cycle benchmarking

- .github/workflows/ci.yml
So that external fork PRs will pass all checks.
> Add condition to check notebooks only on push or from the same repository in CI

- cirq-superstaq/cirq_superstaq/job.py
- cirq-superstaq/cirq_superstaq/job_test.py
Fixes: https://github.com/Infleqtion/client-superstaq/issues/1248
> Update job status priority order to favor 'Running'

- cirq-superstaq/cirq_superstaq/__init__.py
- cirq-superstaq/cirq_superstaq/evaluation.py
- cirq-superstaq/cirq_superstaq/evaluation_test.py
- cirq-superstaq/cirq_superstaq/resource_counters.py
- cirq-superstaq/cirq_superstaq/resource_counters_test.py
Moving resource counters from server.
> Resource counters

- cirq-superstaq/cirq_superstaq/daily_integration_test.py
- qiskit-superstaq/qiskit_superstaq/daily_integration_test.py
confirmation that this passes: https://github.com/Infleqtion/client-superstaq/actions/runs/18173157480/job/51732529532
> fix integration tests for disabled qcvv endpoints
